// <auto-generated />
using System;
using Forge.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Forge.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ForgeDbContext))]
    [Migration("20260822065848_ExercisePersonalisation")]
    partial class ExercisePersonalisation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Forge.Domain.Engagement.Achievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EncouragingDescription")
                        .IsRequired()
                        .HasMaxLength(280)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UnlockedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Achievement");
                });

            modelBuilder.Entity("Forge.Domain.Engagement.Streak", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BestDays")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentDays")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("DeletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("FreezesRemaining")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("GamificationEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("History")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("LastCountedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Streak");
                });

            modelBuilder.Entity("Forge.Domain.Nutrition.Barcodes.FoodBarcode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FoodItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gtin14")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastScannedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provenance")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScannedValue")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbology")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("TimesScanned")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FoodItemId");

                    b.HasIndex("Gtin14")
                        .IsUnique()
                        .HasFilter("\"DeletedUtc\" IS NULL");

                    b.ToTable("FoodBarcode");
                });

            modelBuilder.Entity("Forge.Domain.Nutrition.FoodItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsUserCreated")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Brand");

                    b.HasIndex("Name");

                    b.ToTable("FoodItem");
                });

            modelBuilder.Entity("Forge.Domain.Nutrition.FoodLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ConsumedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FoodItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MealSlot")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConsumedUtc");

                    b.HasIndex("FoodItemId");

                    b.HasIndex("UserProfileId", "ConsumedUtc");

                    b.ToTable("FoodLogEntry");
                });

            modelBuilder.Entity("Forge.Domain.Nutrition.HydrationEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BeverageType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CaffeineMilligrams")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ConsumedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Volume")
                        .HasPrecision(10, 3)
                        .HasColumnType("TEXT")
                        .HasColumnName("VolumeMillilitres");

                    b.HasKey("Id");

                    b.HasIndex("ConsumedUtc");

                    b.HasIndex("UserProfileId", "ConsumedUtc");

                    b.ToTable("HydrationEntry");
                });

            modelBuilder.Entity("Forge.Domain.Nutrition.Recipes.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BaseServings")
                        .HasColumnType("INTEGER");

                    b.Property<double>("CookTime")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double>("PrepTime")
                        .HasColumnType("REAL");

                    b.Property<string>("Provenance")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Recipe");
                });

            modelBuilder.Entity("Forge.Domain.Planning.PlanDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ScheduledDay")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TrainingPlanId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScheduledDay");

                    b.HasIndex("UserProfileId");

                    b.HasIndex("TrainingPlanId", "Ordinal");

                    b.ToTable("PlanDay");
                });

            modelBuilder.Entity("Forge.Domain.Planning.PlannedExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BlockType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ExerciseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupKey")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pattern")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PlanDayId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryMuscle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondaryMuscles")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Pattern");

                    b.HasIndex("UserProfileId");

                    b.HasIndex("PlanDayId", "Ordinal");

                    b.ToTable("PlannedExercise");
                });

            modelBuilder.Entity("Forge.Domain.Planning.PlannedSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsWarmUp")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PlannedExerciseId")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Rest")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TargetLoad")
                        .HasPrecision(10, 3)
                        .HasColumnType("TEXT")
                        .HasColumnName("TargetLoadKilograms");

                    b.Property<int>("TargetRepsMax")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetRepsMin")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("TargetRpe")
                        .HasPrecision(4, 1)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.HasIndex("PlannedExerciseId", "Ordinal");

                    b.ToTable("PlannedSet");
                });

            modelBuilder.Entity("Forge.Domain.Planning.TrainingPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTemplate")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ScheduleMode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetSessionsPerWeek")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsTemplate");

                    b.HasIndex("UserProfileId", "IsActive");

                    b.ToTable("TrainingPlan");
                });

            modelBuilder.Entity("Forge.Domain.Profile.BodyMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("BodyFatPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("BodyFatPercentage");

                    b.Property<decimal?>("ChestCircumference")
                        .HasPrecision(8, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("ChestCentimetres");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("HipCircumference")
                        .HasPrecision(8, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("HipCentimetres");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RecordedUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ThighCircumference")
                        .HasPrecision(8, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("ThighCentimetres");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("WaistCircumference")
                        .HasPrecision(8, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("WaistCentimetres");

                    b.Property<decimal>("Weight")
                        .HasPrecision(10, 3)
                        .HasColumnType("TEXT")
                        .HasColumnName("WeightKilograms");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId", "RecordedUtc");

                    b.ToTable("BodyMetric");
                });

            modelBuilder.Entity("Forge.Domain.Profile.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AvailableEquipment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("BiologicalSex")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("ExperienceLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Goal")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GoalTimeframeWeeks")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Height")
                        .HasPrecision(8, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("HeightCentimetres");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastActivatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MovementLimitations")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TargetDailyCalories")
                        .HasPrecision(8)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TargetWeight")
                        .HasPrecision(10, 3)
                        .HasColumnType("TEXT")
                        .HasColumnName("TargetWeightKilograms");

                    b.Property<int>("TrainingDaysPerWeek")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DisplayName");

                    b.ToTable("UserProfile");
                });

            modelBuilder.Entity("Forge.Domain.Recovery.MorningCheckIn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Energy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Motivation")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("SleepHours")
                        .HasPrecision(4, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Soreness")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stress")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId", "Date")
                        .IsUnique();

                    b.ToTable("MorningCheckIn");
                });

            modelBuilder.Entity("Forge.Domain.Recovery.SorenessEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MuscleGroup")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("RecordedOn")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MuscleGroup", "RecordedOn");

                    b.HasIndex("UserProfileId", "RecordedOn");

                    b.ToTable("SorenessEntry");
                });

            modelBuilder.Entity("Forge.Domain.Training.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CoachingCues")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CommonMistakes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Equipment")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutionSteps")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ForceType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsUnilateral")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsUserCreated")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Pattern")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrimaryMuscle")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SafetyNotes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondaryMuscles")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Equipment");

                    b.HasIndex("Name");

                    b.HasIndex("Pattern");

                    b.ToTable("Exercise");
                });

            modelBuilder.Entity("Forge.Domain.Training.ExerciseProfileState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFavourite")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastUsedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("UserProfileId", "ExerciseId")
                        .IsUnique();

                    b.ToTable("ExerciseProfileState");
                });

            modelBuilder.Entity("Forge.Domain.Training.SetEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<double?>("DistanceMetres")
                        .HasColumnType("REAL");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsWarmUp")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Load")
                        .HasPrecision(10, 3)
                        .HasColumnType("TEXT")
                        .HasColumnName("LoadKilograms");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Repetitions")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RepsInReserve")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ToFailure")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkoutSessionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.HasIndex("WorkoutSessionId");

                    b.HasIndex("ExerciseId", "CompletedUtc");

                    b.HasIndex("UserProfileId", "ExerciseId", "CompletedUtc");

                    b.ToTable("SetEntry");
                });

            modelBuilder.Entity("Forge.Domain.Training.WorkoutSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SessionRpe")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompletedUtc");

                    b.HasIndex("StartedUtc");

                    b.HasIndex("UserProfileId", "CompletedUtc");

                    b.HasIndex("UserProfileId", "StartedUtc");

                    b.ToTable("WorkoutSession");
                });

            modelBuilder.Entity("Forge.Domain.Workout.ActiveWorkoutState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompletedSets")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CurrentExerciseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentExerciseName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExerciseQueue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkoutSessionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompletedUtc");

                    b.HasIndex("UserProfileId");

                    b.HasIndex("WorkoutSessionId")
                        .IsUnique();

                    b.ToTable("ActiveWorkoutState");
                });

            modelBuilder.Entity("Forge.Infrastructure.Persistence.SeedContent.SeedContentImport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CatalogueName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CatalogueName")
                        .IsUnique();

                    b.ToTable("SeedContentImport");
                });

            modelBuilder.Entity("Forge.Domain.Nutrition.Barcodes.FoodBarcode", b =>
                {
                    b.HasOne("Forge.Domain.Nutrition.FoodItem", "Food")
                        .WithMany()
                        .HasForeignKey("FoodItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");
                });

            modelBuilder.Entity("Forge.Domain.Nutrition.FoodItem", b =>
                {
                    b.OwnsOne("Forge.Domain.Nutrition.NutrientProfile", "Per100Grams", b1 =>
                        {
                            b1.Property<Guid>("FoodItemId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("CarbohydrateGrams")
                                .HasPrecision(10, 3)
                                .HasColumnType("TEXT")
                                .HasColumnName("CarbohydrateGramsPer100g");

                            b1.Property<decimal>("EnergyKilocalories")
                                .HasPrecision(10, 2)
                                .HasColumnType("TEXT")
                                .HasColumnName("EnergyKilocaloriesPer100g");

                            b1.Property<decimal>("FatGrams")
                                .HasPrecision(10, 3)
                                .HasColumnType("TEXT")
                                .HasColumnName("FatGramsPer100g");

                            b1.Property<decimal>("FibreGrams")
                                .HasPrecision(10, 3)
                                .HasColumnType("TEXT")
                                .HasColumnName("FibreGramsPer100g");

                            b1.Property<decimal>("ProteinGrams")
                                .HasPrecision(10, 3)
                                .HasColumnType("TEXT")
                                .HasColumnName("ProteinGramsPer100g");

                            b1.Property<decimal>("SodiumMilligrams")
                                .HasPrecision(10, 3)
                                .HasColumnType("TEXT")
                                .HasColumnName("SodiumMilligramsPer100g");

                            b1.Property<decimal>("SugarGrams")
                                .HasPrecision(10, 3)
                                .HasColumnType("TEXT")
                                .HasColumnName("SugarGramsPer100g");

                            b1.HasKey("FoodItemId");

                            b1.ToTable("FoodItem");

                            b1.WithOwner()
                                .HasForeignKey("FoodItemId");
                        });

                    b.OwnsMany("Forge.Domain.Nutrition.ServingDefinition", "Servings", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<Guid>("FoodItemId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Mass")
                                .HasPrecision(10, 6)
                                .HasColumnType("TEXT")
                                .HasColumnName("MassKilograms");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<decimal?>("Volume")
                                .HasPrecision(10, 3)
                                .HasColumnType("TEXT")
                                .HasColumnName("VolumeMillilitres");

                            b1.HasKey("Id");

                            b1.HasIndex("FoodItemId");

                            b1.ToTable("FoodItemServingDefinitions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("FoodItemId");
                        });

                    b.Navigation("Per100Grams")
                        .IsRequired();

                    b.Navigation("Servings");
                });

            modelBuilder.Entity("Forge.Domain.Nutrition.FoodLogEntry", b =>
                {
                    b.HasOne("Forge.Domain.Nutrition.FoodItem", "Food")
                        .WithMany()
                        .HasForeignKey("FoodItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Forge.Domain.Nutrition.ServingSnapshot", "Serving", b1 =>
                        {
                            b1.Property<Guid>("FoodLogEntryId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("GramsPerServing")
                                .HasPrecision(10, 3)
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Quantity")
                                .HasPrecision(10, 3)
                                .HasColumnType("TEXT");

                            b1.Property<string>("ServingName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.HasKey("FoodLogEntryId");

                            b1.ToTable("FoodLogEntry");

                            b1.WithOwner()
                                .HasForeignKey("FoodLogEntryId");
                        });

                    b.Navigation("Food");

                    b.Navigation("Serving")
                        .IsRequired();
                });

            modelBuilder.Entity("Forge.Domain.Nutrition.Recipes.Recipe", b =>
                {
                    b.OwnsMany("Forge.Domain.Nutrition.Recipes.RecipeIngredient", "Ingredients", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<decimal>("EdibleMass")
                                .HasPrecision(10, 6)
                                .HasColumnType("TEXT")
                                .HasColumnName("EdibleMassKilograms");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(160)
                                .HasColumnType("TEXT");

                            b1.Property<string>("PreparationNote")
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Quantity")
                                .HasPrecision(10, 3)
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("RecipeId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("SortOrder")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("TEXT");

                            b1.Property<decimal?>("Volume")
                                .HasPrecision(10, 3)
                                .HasColumnType("TEXT")
                                .HasColumnName("VolumeMillilitres");

                            b1.HasKey("Id");

                            b1.HasIndex("RecipeId");

                            b1.ToTable("RecipeIngredients", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RecipeId");

                            b1.OwnsOne("Forge.Domain.Nutrition.NutrientProfile", "Per100Grams", b2 =>
                                {
                                    b2.Property<int>("RecipeIngredientId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<decimal>("CarbohydrateGrams")
                                        .HasPrecision(10, 3)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("CarbohydrateGramsPer100g");

                                    b2.Property<decimal>("EnergyKilocalories")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("EnergyKilocaloriesPer100g");

                                    b2.Property<decimal>("FatGrams")
                                        .HasPrecision(10, 3)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("FatGramsPer100g");

                                    b2.Property<decimal>("FibreGrams")
                                        .HasPrecision(10, 3)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("FibreGramsPer100g");

                                    b2.Property<decimal>("ProteinGrams")
                                        .HasPrecision(10, 3)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("ProteinGramsPer100g");

                                    b2.Property<decimal>("SodiumMilligrams")
                                        .HasPrecision(10, 3)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("SodiumMilligramsPer100g");

                                    b2.Property<decimal>("SugarGrams")
                                        .HasPrecision(10, 3)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("SugarGramsPer100g");

                                    b2.HasKey("RecipeIngredientId");

                                    b2.ToTable("RecipeIngredients");

                                    b2.WithOwner()
                                        .HasForeignKey("RecipeIngredientId");
                                });

                            b1.Navigation("Per100Grams")
                                .IsRequired();
                        });

                    b.OwnsMany("Forge.Domain.Nutrition.Recipes.RecipeStep", "Steps", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Instruction")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("RecipeId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("SortOrder")
                                .HasColumnType("INTEGER");

                            b1.HasKey("Id");

                            b1.HasIndex("RecipeId");

                            b1.ToTable("RecipeSteps", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RecipeId");
                        });

                    b.OwnsMany("Forge.Domain.Nutrition.Recipes.RecipeTagAssignment", "Tags", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<Guid>("RecipeId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Tag")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("RecipeId");

                            b1.ToTable("RecipeTags", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RecipeId");
                        });

                    b.Navigation("Ingredients");

                    b.Navigation("Steps");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Forge.Domain.Planning.PlanDay", b =>
                {
                    b.HasOne("Forge.Domain.Planning.TrainingPlan", null)
                        .WithMany("Days")
                        .HasForeignKey("TrainingPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Forge.Domain.Planning.PlannedExercise", b =>
                {
                    b.HasOne("Forge.Domain.Planning.PlanDay", null)
                        .WithMany("Exercises")
                        .HasForeignKey("PlanDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Forge.Domain.Planning.PlannedSet", b =>
                {
                    b.HasOne("Forge.Domain.Planning.PlannedExercise", null)
                        .WithMany("Sets")
                        .HasForeignKey("PlannedExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Forge.Domain.Training.SetEntry", b =>
                {
                    b.HasOne("Forge.Domain.Training.WorkoutSession", null)
                        .WithMany("Sets")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Forge.Domain.Workout.ActiveWorkoutState", b =>
                {
                    b.OwnsOne("Forge.Domain.Workout.RestTimer", "ActiveRestTimer", b1 =>
                        {
                            b1.Property<Guid>("ActiveWorkoutStateId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("EndedEarly")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTimeOffset?>("EndedUtc")
                                .HasColumnType("TEXT");

                            b1.Property<int>("NotificationId")
                                .HasColumnType("INTEGER");

                            b1.Property<TimeSpan>("PlannedDuration")
                                .HasColumnType("TEXT");

                            b1.Property<DateTimeOffset>("StartedUtc")
                                .HasColumnType("TEXT");

                            b1.Property<DateTimeOffset>("TargetEndUtc")
                                .HasColumnType("TEXT");

                            b1.HasKey("ActiveWorkoutStateId");

                            b1.ToTable("ActiveWorkoutState");

                            b1.WithOwner()
                                .HasForeignKey("ActiveWorkoutStateId");
                        });

                    b.Navigation("ActiveRestTimer");
                });

            modelBuilder.Entity("Forge.Domain.Planning.PlanDay", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("Forge.Domain.Planning.PlannedExercise", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("Forge.Domain.Planning.TrainingPlan", b =>
                {
                    b.Navigation("Days");
                });

            modelBuilder.Entity("Forge.Domain.Training.WorkoutSession", b =>
                {
                    b.Navigation("Sets");
                });
#pragma warning restore 612, 618
        }
    }
}
