// <auto-generated />
// Generated by tools/legal/Build-LegalSite.ps1 from docs/legal/*.md.
// Do not edit by hand. Edit the Markdown and regenerate, so the in-app copy and the
// published copy at the public legal URL can never disagree.

namespace Forge.App.Features.Legal;

public static class LegalContent
{
    public static IReadOnlyList<LegalSection> PrivacyPolicy { get; } =
    [
        new("Local-first privacy",
            "Forge is a fitness app for Android and iOS, published by [TODO for the publisher: registered legal entity name and, if applicable, company registration number]. Version 1 has no Forge-operated backend, account server or cloud database. Your workouts, body metrics, nutrition logs, goals, preferences and health-platform imports are stored on your device.\n\nForge does not ask you to create an account and cannot identify you. There is no Forge server that receives your data, so there is no Forge copy of it to disclose, sell or lose."),
        new("Health data stays on your device",
            "Health and fitness data can reveal sensitive information about your body and your daily routine. Under the UK and EU General Data Protection Regulation it is special-category data and deserves stricter handling than ordinary app data.\n\nForge does not sell health data, does not use health data for advertising, does not use it for tracking or cross-app profiling, and does not send it to Forge servers. Health data is not stored in iCloud or any other Forge-operated cloud service.\n\nIf you export a backup, produce a diagnostic file or move a file with your operating system's share sheet, you control where that file goes. Once you share or store an exported file outside Forge, that destination's privacy and security rules apply instead of this policy."),
        new("What Forge stores on your device",
            "Forge may store the following categories locally:\n\n- workout plans, exercise history, sets, reps, loads and notes;\n- nutrition, hydration and body metric entries;\n- goals, preferences, units, notification settings and app-lock state;\n- Health Connect or HealthKit values you explicitly allow Forge to read;\n- data you import yourself from another fitness app's export file;\n- a local record of purchases, so paid features stay unlocked without an account;\n- cached media and temporary export files needed for app features.\n\nForge does not collect contacts, precise location, browsing history, advertising identifiers or device identifiers used for tracking."),
        new("Storage and encryption",
            "Forge stores app data in an encrypted local SQLite database using SQLCipher. The database encryption key is held in platform secure storage, which is backed by the Android Keystore and the iOS Keychain. Some non-sensitive settings, such as your preferred units, are stored through the platform preferences system, which is not encrypted by Forge.\n\nDevice-level protection still matters. If someone can unlock your device, they can generally open your apps. Use a device passcode and, if you want a second barrier, turn on Forge's optional app lock."),
        new("Network connections",
            "Forge is designed to work with the network permanently unavailable, and every feature that handles your health data works offline. Forge still needs a network connection for a small number of things that are handled by the platform rather than by Forge:\n\n- purchases, where the App Store or Google Play processes payment and tells the device what you own;\n- optional exercise video packs, which are hosted and served by Apple On-Demand Resources and Google Play Asset Delivery rather than by Forge;\n- app updates, which the store handles in the usual way.\n\nThese requests go to Apple and Google, not to Forge. Like any network request, they reveal your IP address and device information to the store you downloaded Forge from, under that store's own privacy policy. No health, workout or nutrition data is included in them."),
        new("Permissions",
            "Forge asks for a permission only when a feature needs it, and explains why at the moment it asks. Depending on the features you use, Forge may request access to Health Connect or HealthKit, notifications, and files for import and export. You can revoke any of these in Android or iOS settings at any time.\n\nRefusing a permission does not lock you out. Every health and fitness feature remains usable with manual entry when a health platform is unavailable, not configured, or denied."),
        new("Health platform integration",
            "On iOS, Forge can read step count and body mass from HealthKit and can save completed workouts back to HealthKit, but only for the data types you explicitly authorise. On Android, Health Connect integration is not enabled in this version, and health data is entered manually.\n\nHealth platform data read by Forge is stored in the same encrypted local database as everything else and is used only for the feature you enabled it for. Forge does not write health values to logs, and does not share health platform data with any third party."),
        new("Advertising, analytics and tracking",
            "Forge contains no advertising, no advertising SDK and no third-party analytics or crash-reporting service that reports to a server. Forge does not track you across apps or websites operated by other companies, and does not build a profile of you.\n\nDiagnostic information stays on your device and is shared only when you deliberately choose to share it."),
        new("Purchases",
            "If you buy a paid Forge feature, Apple or Google processes the payment. Forge never sees your card details, billing address or store account. Forge stores only a local entitlement record on your device, so paid features stay unlocked without a Forge account server. Your purchase history is held by the store, and you manage refunds and subscriptions there."),
        new("Backups and deletion",
            "Because Forge has no cloud backup, your device is the only system of record. If you uninstall Forge, reset or lose your device, or delete your data without an exported backup, Forge cannot recover it. Nobody at Forge has a copy.\n\nThe in-app Delete my data flow works without contacting support and erases the encrypted local database, the encryption key in secure storage, cached media, preferences and temporary export files. Deletion is irreversible unless you exported and kept your own backup first. You can also erase everything by uninstalling the app. Full instructions, including how to erase Forge data without installing the app, are published on the Delete my data page."),
        new("Your rights",
            "Data protection law gives you rights over your personal data, including access, correction, erasure, restriction, objection and portability.\n\nBecause Forge holds no copy of your data, you exercise these rights directly on your device rather than by asking anyone's permission. Access and portability are provided by the in-app export, which produces open JSON and CSV files. Correction is editing an entry. Erasure is the Delete my data flow, or uninstalling.\n\nIf you email support, the message and address you send become personal data held by [TODO for the publisher: registered legal entity name], processed to answer you and kept no longer than needed. You can ask for that correspondence to be deleted.\n\nThe supervisory authority for complaints is [TODO for the publisher: relevant data protection authority for the publisher's jurisdiction]."),
        new("Children",
            "Forge is intended for general fitness use by adults and is not directed at children. Forge does not knowingly collect data from children. Because Forge has no account system and no server, any data in the app is held on the device by whoever uses it, and a parent or guardian controls it through normal device controls."),
        new("Changes to this policy",
            "This policy may be updated with future app releases. The published version at [TODO for the publisher: final public policy URL, for example https://nikomix.github.io/fitness/privacy/] is always the current one, and always matches the copy shown inside the app. Material changes will be noted with a new effective date."),
        new("Contact",
            "For privacy questions or requests, email [TODO for the publisher: privacy contact email address, for example privacy@yourdomain.example].\n\nThe data controller is [TODO for the publisher: registered legal entity name and registered postal address]."),
    ];

    public static IReadOnlyList<LegalSection> TermsOfService { get; } =
    [
        new("Using Forge",
            "Forge is a local-first fitness app for personal training, nutrition tracking and progress review, published by [TODO for the publisher: registered legal entity name and registered postal address]. By installing or using Forge you accept these terms. If you do not accept them, do not use the app.\n\nYou are responsible for the information you enter, for the training decisions you make, and for keeping your device and your backups secure."),
        new("Not medical advice",
            "Forge provides general fitness and nutrition guidance. It is not medical advice, diagnosis or treatment, and it is not a substitute for a qualified healthcare professional. The medical disclaimer forms part of these terms and you should read it before you train."),
        new("No account and no recovery",
            "Forge v1 has no Forge-operated account system and no cloud database. If you delete the app, erase your data, or lose your device without an exported backup, Forge cannot recover your local data, because Forge never holds a copy of it.\n\nExporting and safeguarding your own backups is your responsibility. Forge provides the export tools; it cannot provide the copy."),
        new("Purchases",
            "Paid Forge features are sold through the App Store and Google Play. The store shows the final local price before purchase, handles taxes and payment, and provides the account used by Restore purchases.\n\nRefunds, chargebacks and subscription cancellations are governed by the store's own policies and are handled by the store, not by Forge. Forge cannot issue a refund on a store's behalf."),
        new("Entitlements",
            "Forge stores purchase entitlements locally on your device. Secure storage and signing make casual edits evident, but without a Forge backend a determined device owner may still tamper with local state. Forge does not promise, and does not attempt, server-grade licence enforcement.\n\nCircumventing or attempting to circumvent the store purchase system is a breach of these terms."),
        new("Acceptable use",
            "Do not use Forge in a way that:\n\n- breaks the law or infringes anyone's rights;\n- attempts to bypass app-store purchase systems or licence checks;\n- reverse engineers the app except to the extent that law expressly permits;\n- redistributes, resells or sublicenses the app or its bundled content; or\n- endangers you or another person."),
        new("Content and intellectual property",
            "Forge, including its exercise catalogue, nutrition data, text, design and software, is owned by the publisher or licensed to it, and is protected by intellectual property law. You get a personal, non-exclusive, non-transferable, revocable licence to use the app on devices you own or control.\n\nThe data you enter is yours. The publisher claims no ownership of it and, having no server, has no access to it."),
        new("Third-party software",
            "Forge includes third-party components under their own licences, listed on the licences page. Those licences continue to apply to those components."),
        new("Availability",
            "Forge is provided as-is. Because it runs entirely on your device, it is not a hosted service and no uptime is promised. Features may change or be removed in later releases, and support for older operating system versions may end."),
        new("Disclaimer and liability",
            "To the fullest extent permitted by law, Forge is provided without warranties of any kind, express or implied, including fitness for a particular purpose, accuracy of fitness or nutrition calculations, and uninterrupted or error-free operation.\n\nTo the fullest extent permitted by law, the publisher is not liable for indirect, incidental, special or consequential loss, for loss of data arising from device loss, device failure, uninstall or deletion, or for injury arising from exercise undertaken contrary to the medical disclaimer.\n\nNothing in these terms limits liability for death or personal injury caused by negligence, for fraud, or for any other liability that cannot lawfully be limited. If you are a consumer, you keep all statutory rights that cannot be excluded by contract."),
        new("Termination",
            "You may stop using Forge at any time by deleting your data or uninstalling. The publisher may end your licence if you materially breach these terms, in which case you must stop using the app. Uninstalling does not entitle you to a refund from the publisher, since the store handles payment."),
        new("Governing law",
            "These terms are governed by the law of [TODO for the publisher: governing law, for example the laws of England and Wales], and the courts of [TODO for the publisher: courts having jurisdiction] have jurisdiction. If you are a consumer, you may also have the right to bring proceedings in your country of residence."),
        new("Changes",
            "These terms may be updated with app releases. The published version is the current one. Continued use after an update means you accept the updated terms."),
        new("Contact",
            "Questions about these terms: [TODO for the publisher: legal contact email address]."),
    ];

    public static IReadOnlyList<LegalSection> MedicalDisclaimer { get; } =
    [
        new("Not medical advice",
            "Forge provides exercise, nutrition and habit guidance for general fitness. It is not medical advice, diagnosis, treatment or a substitute for a qualified healthcare professional. No content in Forge creates a clinician-patient relationship, and Forge cannot assess your individual health."),
        new("Before starting",
            "Consult a physician, physiotherapist, dietitian or other qualified professional before starting a new programme, increasing training intensity, materially changing your diet, or using Forge after a period of inactivity."),
        new("Pain or warning symptoms",
            "Stop exercising immediately if you experience chest pain, faintness, severe shortness of breath, an unusual heart rhythm, sharp joint pain, sudden weakness, dizziness or any symptom that feels unsafe. Seek urgent medical care when symptoms are severe or persistent.\n\nForge cannot detect a medical emergency and must never be relied on to do so. In an emergency, contact your local emergency services."),
        new("Pregnancy",
            "If you are pregnant, recently gave birth or are trying to conceive, get professional guidance before following exercise or nutrition recommendations. Training intensity, hydration, calorie targets and movement selection may all need individual adjustment."),
        new("Cardiac conditions",
            "If you have a heart condition, high blood pressure, a history of cardiac events, an implanted cardiac device, or have been advised to limit exertion, use Forge only with professional clearance, and follow your clinician's limits over any suggestion the app makes."),
        new("Injury and rehabilitation",
            "If you are injured, recovering from surgery or managing chronic pain, avoid movements that aggravate symptoms and follow your clinician or therapist's rehabilitation plan. Forge cannot assess tissue healing or judge safe loading for you."),
        new("Nutrition and hydration targets",
            "Calorie, macronutrient and hydration figures in Forge are general estimates from standard formulas. They are not clinical prescriptions and do not account for medication, pregnancy, eating disorders, diabetes, kidney or liver conditions, or other individual factors. Seek professional advice before acting on them if any of these apply to you."),
        new("Accuracy of imported and calculated data",
            "Values imported from Health Connect, HealthKit or another app's export are only as accurate as the device or app that produced them. Estimates such as calories burned are approximations, not measurements, and should not be used for any clinical purpose."),
        new("Your responsibility",
            "You use Forge at your own risk, and you are responsible for training within your own limits. If any guidance conflicts with advice from your healthcare professional, follow your healthcare professional."),
    ];

    public static IReadOnlyList<LegalSection> Licences { get; } =
    [
        new("About this page",
            "Forge is built on third-party components, each covered by its own licence. Those licences continue to apply to those components and are not replaced by Forge's own terms.\n\nThe authoritative list of packages and exact versions is the dependency manifest in the Forge repository. This page summarises the significant components."),
        new("DevExpress .NET MAUI",
            "Forge uses DevExpress MAUI controls for mobile user interface surfaces, under the DevExpress commercial licence terms applicable to the package version in use."),
        new("CommunityToolkit",
            "Forge uses CommunityToolkit.Mvvm and CommunityToolkit.Maui components under their open-source licence terms, published by the .NET Foundation and contributors."),
        new("Entity Framework Core",
            "Forge uses Microsoft Entity Framework Core for local persistence access, under Microsoft's open-source licence terms."),
        new("SQLite and SQLCipher",
            "Forge stores local data in SQLite. SQLite is in the public domain. Encryption is supplied by the SQLCipher bundle configured in the persistence layer, under its own licence terms."),
        new(".NET and .NET MAUI",
            "Forge is built on the .NET platform and .NET MAUI, published by Microsoft and the .NET Foundation under the MIT licence."),
        new("Attribution",
            "Before each store submission, verify exact package names, versions and licence texts from the dependency lock files and include any notices those licences require. [TODO for the publisher: confirm the final component list and paste any licence notices that must be reproduced verbatim, particularly for DevExpress and the SQLCipher bundle]."),
    ];
}

